services:
  minio:
    image: minio/minio:latest
    container_name: test_imu_minio
    ports:
      - "19000:9000"
      - "19001:9001"
    environment:
      - "MINIO_ROOT_USER=test"
      - "MINIO_ROOT_PASSWORD=imtestinguser"
      - "MINIO_SERVER_URL=http://localhost:9000"
    command: ['server', '/storage', '--console-address', ':9001']
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 2s
      timeout: 20s
      retries: 5
  mc:
    image: minio/mc:latest
    container_name: test_imu_minio_md
    depends_on:
      minio:
        condition: service_healthy
    environment:
      - "MINIO_ROOT_USER=test"
      - "MINIO_ROOT_PASSWORD=imtestinguser"
    entrypoint: >
      /bin/sh -c "

      mc alias set mdstore http://minio:19000 test imtestinguser;

      mc mb test/test;
      "

    volumes:
      - /test_minio_container/data
