services:
  minio:
    image: minio/minio:latest
    container_name: imu_minio
    ports:
      - "${MINIO_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
    environment:
      - "MINIO_ROOT_USER=${MINIO_ROOT_USER}"
      - "MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}"
      - "MINIO_SERVER_URL=http://${MINIO_SERVER_URL:-localhost:9000}"
    command: ['server', '/storage', '--console-address', ':9001']
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 2s
      timeout: 20s
      retries: 5
  mc:
    image: minio/mc:latest
    container_name: imu_minio_md
    depends_on:
      minio:
        condition: service_healthy
    environment:
      - "MINIO_ROOT_USER=${MINIO_ROOT_USER}"
      - "MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}"
    entrypoint: >
      /bin/sh -c "

      mc alias set mdstore http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};

      mc mb ${MDFILESYSTEM}/${MDBUCKET};
      "

    volumes:
      - ${POOL_PATH}
