// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
	"time"
)

type User struct {
	ID       string         `json:"id"`
	Name     string         `json:"name"`
	Bio      sql.NullString `json:"bio"`
	Since    time.Time      `json:"since"`
	Email    string         `json:"email"`
	Password string         `json:"password"`
}
