// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Img struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

type Markdown struct {
	ID          uuid.UUID `json:"id"`
	StudentID   string    `json:"student_id"`
	Title       string    `json:"title"`
	ContentPath string    `json:"content_path"`
	Since       time.Time `json:"since"`
	Updated     time.Time `json:"updated"`
}

type MarkdownImgRel struct {
	MarkdownID uuid.UUID `json:"markdown_id"`
	ImgID      uuid.UUID `json:"img_id"`
}

type Student struct {
	ID       string         `json:"id"`
	Name     string         `json:"name"`
	Bio      sql.NullString `json:"bio"`
	Since    time.Time      `json:"since"`
	Email    string         `json:"email"`
	Password string         `json:"password"`
	ImgPath  uuid.NullUUID  `json:"img_path"`
}
