CREATE TABLE student (
    id          VARCHAR(126) PRIMARY KEY NOT NULL,
    name        VARCHAR(126) NOT NULL,
    bio         VARCHAR(510),
    since       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    email       VARCHAR(126) NOT NULL UNIQUE,
    password    CHAR(60) NOT NULL
);

CREATE TABLE markdown_img_rel (
    markdown_id BIGINT NOT NULL,
    img_id      BIGINT NOT NULL,
    FOREIGN KEY (markdown_id) REFERENCES markdown(id),
    FOREIGN KEY (img_id) REFERENCES img(id),
    PRIMARY KEY (markdown_id, img_id)
);

CREATE TABLE img (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name        VARCHAR(126) NOT NULL,
    img_path    VARCHAR(255) NOT NULL
);

CREATE TABLE markdown (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    student_id      VARCHAR(126) NOT NULL,
    title           VARCHAR(126) NOT NULL,
    content_path    VARCHAR(255) NOT NULL,
    since           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY     (student_id) REFERENCES student(id)
);
